-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 20:23:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tp_php
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tp_php` ;

-- -----------------------------------------------------
-- Schema tp_php
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tp_php` DEFAULT CHARACTER SET utf8 ;
USE `tp_php` ;

-- -----------------------------------------------------
-- Table `tp_php`.`Auteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tp_php`.`Auteur` ;

CREATE TABLE IF NOT EXISTS `tp_php`.`Auteur` (
  `idAuteur` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prénom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAuteur`),
  UNIQUE INDEX `idAuteur_UNIQUE` (`idAuteur` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tp_php`.`Ecrit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tp_php`.`Ecrit` ;

CREATE TABLE IF NOT EXISTS `tp_php`.`Ecrit` (
  `Auteur_idAuteur` INT NOT NULL,
  `Livres_idLivres` INT NOT NULL,
  PRIMARY KEY (`Auteur_idAuteur`, `Livres_idLivres`),
  INDEX `fk_Ecrit_Livres1_idx` (`Livres_idLivres` ASC) VISIBLE,
  CONSTRAINT `fk_Ecrit_Auteur`
    FOREIGN KEY (`Auteur_idAuteur`)
    REFERENCES `tp_php`.`Auteur` (`idAuteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ecrit_Livres1`
    FOREIGN KEY (`Livres_idLivres`)
    REFERENCES `tp_php`.`Livres` (`idLivres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tp_php`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tp_php`.`Genre` ;

CREATE TABLE IF NOT EXISTS `tp_php`.`Genre` (
  `idGenre` INT NOT NULL AUTO_INCREMENT,
  `Libellé` VARCHAR(45) NOT NULL,
  `Description` MEDIUMTEXT NULL,
  PRIMARY KEY (`idGenre`),
  UNIQUE INDEX `idGenre_UNIQUE` (`idGenre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tp_php`.`Livres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tp_php`.`Livres` ;

CREATE TABLE IF NOT EXISTS `tp_php`.`Livres` (
  `idLivres` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(45) NOT NULL,
  `Description` MEDIUMTEXT NULL,
  `Image` BLOB NOT NULL,
  PRIMARY KEY (`idLivres`),
  UNIQUE INDEX `idLivres_UNIQUE` (`idLivres` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tp_php`.`Possède`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tp_php`.`Possède` ;

CREATE TABLE IF NOT EXISTS `tp_php`.`Possède` (
  `Livres_idLivres` INT NOT NULL,
  `Genre_idGenre` INT NOT NULL,
  PRIMARY KEY (`Livres_idLivres`, `Genre_idGenre`),
  INDEX `fk_Possède_Genre1_idx` (`Genre_idGenre` ASC) VISIBLE,
  CONSTRAINT `fk_Possède_Livres1`
    FOREIGN KEY (`Livres_idLivres`)
    REFERENCES `tp_php`.`Livres` (`idLivres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Possède_Genre1`
    FOREIGN KEY (`Genre_idGenre`)
    REFERENCES `tp_php`.`Genre` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS user1;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
